{
 "title": "Kubernetes Cluster Autoscaler Multicluster",
 "description": "Super simple dashboard showing an overview of kubernetes cluster autoscaling activity and status, using metrics reported by the autoscaler to prometheus.\r\n\r\nhttps://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(cluster_autoscaler_nodes_count, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_nodes_count{cluster=~\"$cluster\"})\n"
    }
   ]
  },
  {
   "title": "Nodes available",
   "type": "gauge",
   "description": "Shows the nodes which are ready as a percent of the total nodes",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_nodes_count{cluster=~\"$cluster\", state=\"ready\"})/sum(cluster_autoscaler_nodes_count{cluster=~\"$cluster\"})*100"
    }
   ]
  },
  {
   "title": "Is cluster safe to scale?",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_cluster_safe_to_autoscale{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Number of unscheduled pods",
   "type": "stat",
   "description": "Tells you if there are unscheduled pods",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_unschedulable_pods_count{cluster=~\"$cluster\"})",
     "legendFormat": " pods"
    }
   ]
  },
  {
   "title": "Last scaleDown activity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time()-cluster_autoscaler_last_activity{cluster=~\"$cluster\", activity=\"scaleDown\"})"
    }
   ]
  },
  {
   "title": "Last autoscale activity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time()-cluster_autoscaler_last_activity{cluster=~\"$cluster\", activity=\"autoscaling\"})"
    }
   ]
  },
  {
   "title": "Pod activity",
   "type": "graph",
   "description": "Shows the evicted and unscheduled pods",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none", "label": "Num Nodes" }
   ],
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_evicted_pods_total{cluster=~\"$cluster\"})",
     "legendFormat": "evicted pods"
    },
    {
     "expr": "sum(cluster_autoscaler_unschedulable_pods_count{cluster=~\"$cluster\"})",
     "legendFormat": "unscheduled pods"
    }
   ]
  },
  {
   "title": "Node activity",
   "type": "graph",
   "description": "Shows the state of the nodes as scaling happens",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "none", "label": "Num Nodes" }
   ],
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_nodes_count{cluster=~\"$cluster\", state=\"ready\"})",
     "legendFormat": "ready"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count{cluster=~\"$cluster\", state=\"unready\"})",
     "legendFormat": "unready"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count{cluster=~\"$cluster\", state=\"notStarted\"})\n",
     "legendFormat": "not started"
    }
   ]
  },
  {
   "title": "Autoscaling activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none", "label": "Num nodes" }
   ],
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_scaled_up_nodes_total{cluster=~\"$cluster\"})",
     "legendFormat": "scaled up total"
    },
    {
     "expr": "sum(cluster_autoscaler_unneeded_nodes_count{cluster=~\"$cluster\"})",
     "legendFormat": "unneeded nodes"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count{cluster=~\"$cluster\"})\n",
     "legendFormat": "total nodes"
    }
   ]
  },
  {
   "title": "Cluster direction?",
   "type": "stat",
   "description": "Is the cluster scaling up, down or ticking along okay?",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_scaled_up_nodes_total{cluster=~\"$cluster\"})-sum(cluster_autoscaler_scaled_down_nodes_total{cluster=~\"$cluster\"})"
    }
   ]
  }
 ]
}