// Copyright (c) 2025 Gitpod GmbH. All rights reserved.
// Licensed under the GNU Affero General Public License (AGPL).
// See License.AGPL.txt in the project root for license information.

// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: devpod/experimental/v1/tokens.proto
//
package io.devpod.publicapi.experimental.v1

import com.connectrpc.Headers
import com.connectrpc.MethodSpec
import com.connectrpc.ProtocolClientInterface
import com.connectrpc.ResponseMessage
import com.connectrpc.StreamType

public class TokensServiceClient(
  private val client: ProtocolClientInterface,
) : TokensServiceClientInterface {
  /**
   *  CreatePersonalAccessTokenRequest creates a new token.
   */
  override suspend fun createPersonalAccessToken(request: Tokens.CreatePersonalAccessTokenRequest,
      headers: Headers): ResponseMessage<Tokens.CreatePersonalAccessTokenResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "devpod.experimental.v1.TokensService/CreatePersonalAccessToken",
      io.devpod.publicapi.experimental.v1.Tokens.CreatePersonalAccessTokenRequest::class,
      io.devpod.publicapi.experimental.v1.Tokens.CreatePersonalAccessTokenResponse::class,
      StreamType.UNARY,
    ),
  )


  /**
   *  ListPersonalAccessTokens returns token by ID.
   */
  override suspend fun getPersonalAccessToken(request: Tokens.GetPersonalAccessTokenRequest,
      headers: Headers): ResponseMessage<Tokens.GetPersonalAccessTokenResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "devpod.experimental.v1.TokensService/GetPersonalAccessToken",
      io.devpod.publicapi.experimental.v1.Tokens.GetPersonalAccessTokenRequest::class,
      io.devpod.publicapi.experimental.v1.Tokens.GetPersonalAccessTokenResponse::class,
      StreamType.UNARY,
    ),
  )


  /**
   *  ListPersonalAccessTokens returns a list of tokens.
   */
  override suspend fun listPersonalAccessTokens(request: Tokens.ListPersonalAccessTokensRequest,
      headers: Headers): ResponseMessage<Tokens.ListPersonalAccessTokensResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "devpod.experimental.v1.TokensService/ListPersonalAccessTokens",
      io.devpod.publicapi.experimental.v1.Tokens.ListPersonalAccessTokensRequest::class,
      io.devpod.publicapi.experimental.v1.Tokens.ListPersonalAccessTokensResponse::class,
      StreamType.UNARY,
    ),
  )


  /**
   *  RegeneratePersonalAccessToken generates a new token and replaces the previous one.
   */
  override suspend
      fun regeneratePersonalAccessToken(request: Tokens.RegeneratePersonalAccessTokenRequest,
      headers: Headers): ResponseMessage<Tokens.RegeneratePersonalAccessTokenResponse> =
      client.unary(
    request,
    headers,
    MethodSpec(
    "devpod.experimental.v1.TokensService/RegeneratePersonalAccessToken",
      io.devpod.publicapi.experimental.v1.Tokens.RegeneratePersonalAccessTokenRequest::class,
      io.devpod.publicapi.experimental.v1.Tokens.RegeneratePersonalAccessTokenResponse::class,
      StreamType.UNARY,
    ),
  )


  /**
   *  UpdatePersonalAccessToken updates writable properties of a PersonalAccessToken.
   */
  override suspend fun updatePersonalAccessToken(request: Tokens.UpdatePersonalAccessTokenRequest,
      headers: Headers): ResponseMessage<Tokens.UpdatePersonalAccessTokenResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "devpod.experimental.v1.TokensService/UpdatePersonalAccessToken",
      io.devpod.publicapi.experimental.v1.Tokens.UpdatePersonalAccessTokenRequest::class,
      io.devpod.publicapi.experimental.v1.Tokens.UpdatePersonalAccessTokenResponse::class,
      StreamType.UNARY,
    ),
  )


  /**
   *  DeletePersonalAccessToken removes token by ID.
   */
  override suspend fun deletePersonalAccessToken(request: Tokens.DeletePersonalAccessTokenRequest,
      headers: Headers): ResponseMessage<Tokens.DeletePersonalAccessTokenResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "devpod.experimental.v1.TokensService/DeletePersonalAccessToken",
      io.devpod.publicapi.experimental.v1.Tokens.DeletePersonalAccessTokenRequest::class,
      io.devpod.publicapi.experimental.v1.Tokens.DeletePersonalAccessTokenResponse::class,
      StreamType.UNARY,
    ),
  )

}
