{
 "title": "Meta Overview",
 "tags": [ "devpod-mixin" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Meta cluster",
    "query": {
     "query": "label_values(up{cluster=~\".*meta.*\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(devpod_server_api_calls_total{cluster=~\"$cluster\"}[5m])) by (cluster, method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "API Request Error rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(devpod_server_api_calls_total{cluster=~\"$cluster\", statusCode!~\"2..|429\"}[5m])\n) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Websocket connections by client type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(server_websocket_connection_count{cluster=~\"$cluster\"}) by (cluster, clientType)",
     "legendFormat": "{{cluster}} {{clientType}}"
    }
   ]
  },
  {
   "title": "Team slot method calls",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 10 },
   "targets": [
    {
     "current": {
      "selected": false,
      "text": "VictoriaMetrics",
      "value": "VictoriaMetrics"
     },
     "name": "datasource",
     "query": "prometheus",
     "refresh": 1,
     "type": "datasource"
    },
    {
     "expr": "sum(rate(devpod_server_api_calls_total{cluster=~\"$cluster\", method=~\"ts.*\"}[5m])) by (cluster, method) * 60",
     "legendFormat": "{{cluster}} {{method}}"
    }
   ]
  },
  {
   "title": "Instance Start Success/Failure Rates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (irate(devpod_server_instance_starts_success_total{cluster=~\"$cluster\"}[2m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum (irate(devpod_server_instance_starts_failed_total{cluster=~\"$cluster\"}[2m])) by (reason)",
     "legendFormat": "Failed because: {{ reason }}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (devpod_version_info{cluster=~\"$cluster\"}) by (cluster, devpod_version)",
     "legendFormat": "{{ cluster }}: {{ devpod_version }}"
    }
   ]
  },
  {
   "title": "External metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Workspace failure rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(\n  rate(devpod_ws_manager_mk2_workspace_stops_total{cluster=~\"$cluster\", reason=\"failed\"}[5m])\n) by (cluster, type)\n",
     "legendFormat": "{{cluster}} {{type}}"
    }
   ]
  }
 ]
}