{
 "title": "Workspace Pressure Stall Information",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(devpod_ws_daemon_workspace_cpu_psi_total_seconds,cluster)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(devpod_ws_daemon_workspace_cpu_psi_total_seconds{cluster=\"$cluster\"},node)"
    }
   },
   {
    "name": "workspace",
    "query": {
     "query": "label_values(devpod_ws_daemon_workspace_cpu_psi_total_seconds{cluster=\"$cluster\",node=\"$node\"},workspace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(devpod_ws_daemon_workspace_cpu_psi_total_seconds{cluster=\"$cluster\", node=\"$node\", workspace=~\"$workspace\"}[10s]/1000000)",
     "legendFormat": "{{workspace}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(devpod_ws_daemon_workspace_memory_psi_total_seconds{cluster=\"$cluster\", node=\"$node\", workspace=~\"$workspace\"}[10s]/1000000)",
     "legendFormat": "{{workspace}}"
    }
   ]
  },
  {
   "title": "IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(devpod_ws_daemon_workspace_io_psi_total_seconds{cluster=\"$cluster\", node=\"$node\", workspace=~\"$workspace\"}[10s]/1000000)",
     "legendFormat": "{{workspace}}"
    }
   ]
  }
 ]
}