{
 "title": "VS Code Browser Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "operation",
    "query": {
     "query": "label_values(devpod_vscode_extension_gallery_operation_total, operation)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "gallery",
    "query": {
     "query": "label_values(devpod_vscode_extension_gallery_operation_total, galleryHost)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Browser Workbench", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load Failed Ratio",
   "type": "timeseries",
   "description": "VSCode Web workbench resources load failed ratio",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(devpod_vscode_web_load_total{status='failed'}[2m])) /sum(rate(devpod_vscode_web_load_total{status='loading'}[2m]))",
     "legendFormat": "total_ratio"
    }
   ]
  },
  { "title": "Extension Gallery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(devpod_vscode_extension_gallery_query_total{galleryHost=~\"$gallery\"}[2m]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(devpod_vscode_extension_gallery_query_duration_seconds_bucket{galleryHost=~\"$gallery\"}[1m])) by (le))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(devpod_vscode_extension_gallery_query_duration_seconds_bucket{galleryHost=~\"$gallery\"}[1m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(devpod_vscode_extension_gallery_query_duration_seconds_bucket{galleryHost=~\"$gallery\"}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(devpod_vscode_extension_gallery_query_duration_seconds_bucket{galleryHost=~\"$gallery\"}[1m])) by (le))",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "total failure ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(devpod_vscode_extension_gallery_query_total{status=\"failure\",errorCode!=\"canceled\",galleryHost=~\"$gallery\"}[2m]))/sum(rate(devpod_vscode_extension_gallery_query_total{galleryHost=~\"$gallery\"}[2m]))",
     "legendFormat": "total ratio"
    }
   ]
  },
  {
   "title": "failure ratio by status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (statusCode) (rate(devpod_vscode_extension_gallery_query_total{status=\"failure\",errorCode!=\"canceled\",galleryHost=~\"$gallery\"}[2m]))/ignoring(statusCode) group_left sum(rate(devpod_vscode_extension_gallery_query_total{galleryHost=~\"$gallery\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "failure ratio by error code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (errorCode) (rate(devpod_vscode_extension_gallery_query_total{status=\"failure\",galleryHost=~\"$gallery\"}[2m]))/ignoring(errorCode) group_left sum(rate(devpod_vscode_extension_gallery_query_total{galleryHost=~\"$gallery\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Extension Management", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(devpod_vscode_extension_gallery_operation_total{operation=~\"$operation\",galleryHost=~\"$gallery\"}[2m]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "total failure ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(devpod_vscode_extension_gallery_operation_total{status=\"failure\",operation=~\"$operation\",galleryHost=~\"$gallery\"}[2m]))/sum(rate(devpod_vscode_extension_gallery_operation_total{operation=~\"$operation\",galleryHost=~\"$gallery\"}[2m]))",
     "legendFormat": "total ratio"
    }
   ]
  },
  {
   "title": "failure ratio by operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(devpod_vscode_extension_gallery_operation_total{status=\"failure\",operation=~\"$operation\",galleryHost=~\"$gallery\"}[2m]))/ignoring(operation) group_left sum(rate(devpod_vscode_extension_gallery_operation_total{operation=~\"$operation\",galleryHost=~\"$gallery\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "total latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(devpod_vscode_extension_gallery_operation_duration_seconds_bucket{operation=~\"$operation\",galleryHost=~\"$gallery\"}[1m])) by (le))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(devpod_vscode_extension_gallery_operation_duration_seconds_bucket{operation=~\"$operation\",galleryHost=~\"$gallery\"}[1m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(devpod_vscode_extension_gallery_operation_duration_seconds_bucket{operation=~\"$operation\",galleryHost=~\"$gallery\"}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(devpod_vscode_extension_gallery_operation_duration_seconds_bucket{operation=~\"$operation\",galleryHost=~\"$gallery\"}[1m])) by (le))",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "operation latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(devpod_vscode_extension_gallery_operation_duration_seconds_bucket{operation=~\"$operation\",galleryHost=~\"$gallery\"}[1m])) by (le, operation))",
     "legendFormat": "{{operation}} - max"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(devpod_vscode_extension_gallery_operation_duration_seconds_bucket{operation=~\"$operation\",galleryHost=~\"$gallery\"}[1m])) by (le, operation))",
     "legendFormat": "{{operation}} - P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(devpod_vscode_extension_gallery_operation_duration_seconds_bucket{operation=~\"$operation\",galleryHost=~\"$gallery\"}[1m])) by (le, operation))",
     "legendFormat": "{{operation}} - P95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(devpod_vscode_extension_gallery_operation_duration_seconds_bucket{operation=~\"$operation\",galleryHost=~\"$gallery\"}[1m])) by (le, operation))",
     "legendFormat": "{{operation}} - mean"
    }
   ]
  }
 ]
}